### ISSUE TITLE
Deletion of digest doesn't work from admin UI

### ISSUE THREAD

**Issue by amitsaxena** [mhenrixon/sidekiq-unique-jobs#438] opened 2019-11-06 22:47 UTC
**Describe the bug**
When I try to delete a digest from sidekiq dashboard under `unique digests` tab, nothing happens and the digest stays. I am talking about this interface:
<img width="443" alt="unique_digests_1" src="https://user-images.githubusercontent.com/65611/68344433-47cca880-00ef-11ea-8eba-581864774f3e.png">

The digests I was trying to delete were some stuck locks preventing further jobs from being scheduled. I eventually had to delete the keys manually from redis.

I am using sidekiq-unique-jobs version 6.0.13

**Expected behavior**
The digest should be deleted and disappear from that page

**Current behavior**
The digest isn't deleted and stays on the page and the keys are still present in redis

**Comment by mhenrixon** [comment] 2019-11-15 09:17
Super weird, are you using rails, sinatra, rack, grape? How do you run sidekiq web?

**Comment by amitsaxena** [comment] 2019-11-16 01:17
I am using `Rails 5.2.2.1`. We mount it as per the standard recommendation:
```
require "sidekiq/pro/web"
require "sidekiq_unique_jobs/web"
mount Sidekiq::Web => "/sidekiq"
```

**Comment by amitsaxena** [comment] 2019-11-20 14:48
I am not sure if it's related, but I also see warnings like this:
```
[13] pry(main)> SidekiqUniqueJobs::Digests.del(digest: "5afaacdbee7148e90cea3c15de700f21")
Passing 'script' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /Users/amit/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/sidekiq-unique-jobs-6.0.15/lib/sidekiq_unique_jobs/scripts.rb:73:in `script_sha')
2019-11-20T14:44:56.252Z pid=79457 tid=oxqpmk67d INFO: delete_by_digest(5afaacdbee7148e90cea3c15de700f21) completed in 0.02ms
=> 1
```

**Comment by mhenrixon** [comment] 2019-11-26 10:56
Will be released as `v6.0.17` shortly

**Comment by mhenrixon** [comment] 2019-11-26 11:49
Released a fix as `v6.0.17`

**Comment by amitsaxena** [comment] 2019-12-09 09:30
This doesn't seem to be fixed for us. We are currently on version `6.0.18`.

**Comment by mhenrixon** [comment] 2019-12-09 10:33
Do you still have the same warnings in your logs @amitsaxena?

**Comment by amitsaxena** [comment] 2019-12-09 23:17
@mhenrixon Yes I still see the same warning.

**Comment by mhenrixon** [comment] 2020-03-21 20:40
@amitsaxena the problem is with redis-namespace preventing this. The way sidekiq wires up redis-namespace prevents this gem from working properly. If you have any suggestions I'm all ears but currently my commands won't work because I can't use redis-namespace with lua scripts and the gem is all about lua scripts.

**Comment by mhenrixon** [comment] 2020-03-21 20:46
This is documented here https://github.com/resque/redis-namespace#administrative-commands and I see no way to fix this in an easy way. I would have to manually namespace the keys somehow and I'm not sure I want to support that. 

Mike Perham recommended strongly against using redis-namespace already back in 2015 https://www.mikeperham.com/2015/09/24/storing-data-with-redis/ and then went on to provide a migration solution towards not using it in https://www.mikeperham.com/2017/04/10/migrating-from-redis-namespace/.

I imagine he recommends against it for a reason (sidekiq-pro sidekiq-ent relies on Lua scripts to do the heavy lifting). Sorry about that.

**Comment by mhenrixon** [comment] 2020-03-21 20:47
Closing due to limitations in `redis-namespace`.

**Closed by mhenrixon** 2020-03-21 20:47 UTC
Labels: bug, v6.x
