### ISSUE TITLE
Please keep some recent versions on rubygems.org

### ISSUE THREAD

**Issue by ziguzagu** [mhenrixon/sidekiq-unique-jobs#478] opened 2020-03-22 02:54 UTC
**Is your feature request related to a problem? Please describe.**

Immediately after v6.0.19 was released, the latest version of v6.0.18 was removed, causing `bundle install` to fail and our deployment to begin to fail on the weekend...

**Describe the solution you'd like**

We want to keep some of the latest versions of rubygems.org, at least two of them.

Thanks for developing useful gem.

**Comment by mhenrixon** [comment] 2020-03-22 10:58
Sorry, it was late last night when I fixed some bugs. I was going to release new versions with a gem install warning but I forgot the last step. 

Will fix immediately, sorry about that

**Comment by mhenrixon** [comment] 2020-03-22 11:18
Alright! All gems re-released with a post-install message as intended.

Please see:

1. https://github.com/mhenrixon/sidekiq-unique-jobs/issues/435
2. https://github.com/mhenrixon/sidekiq-unique-jobs/issues/471

For information about the issue (in case you are still using `unique: :lock_type`.

**Closed by mhenrixon** 2020-03-22 11:18 UTC

**Comment by mhenrixon** [comment] 2020-03-25 08:28
Unfortunately, like stated in the linked issue (#480) I cannot re-release a gem. I am powerless to change that. 

```ruby
gem 'sidekiq-unique-jobs', git: 'https://github.com/mhenrixon/sidekiq-unique-jobs', tag: 'v6.0.18'
```

Was how someone solved the issue. It is 100% safe to upgrade though, you can read about the change in the changelog: 

1. [v6.0.20](https://github.com/mhenrixon/sidekiq-unique-jobs/blob/master/CHANGELOG.md#v6020-2020-03-22)
2. [v6.0.19](https://github.com/mhenrixon/sidekiq-unique-jobs/blob/master/CHANGELOG.md#v6019-2020-03-21)

I'd go with the upgrade, if that doesn't work you can do what @vitalinfo did and fixate the gem version like above: https://github.com/mhenrixon/sidekiq-unique-jobs/issues/480#issuecomment-602196923.

I am terribly sorry about this, my understanding of how gem releases work wasn't accurate. We live, and we learn!

This obviously will not happen again :)

**Comment by robinsingh-bw** [comment] 2020-06-11 17:58
@mhenrixon I am seeing duplicate jobs with until_and_while_executing on version 6.0.22, had 6.0.15 earlier and it was working flawlessly. Any idea what could be causing this in the new versions?  I am reverting to 6.0.15 for now.
